server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        # Authentication Service
        - id: auth-service
          uri: http://localhost:8076
          predicates:
            - Path=/api/auth/**
          

        # Prescription Service - List
        - id: prescription-list
          uri: http://localhost:8081
          predicates:
            - Path=/api/prescriptions
          filters:
            - RewritePath=/api/prescriptions, /api/v1/prescription

        # Prescription Service - Detail
        - id: prescription-detail
          uri: http://localhost:8081
          predicates:
            - Path=/api/prescriptions/**
          filters:
            - RewritePath=/api/prescriptions/(?<segment>.*), /api/v1/prescription/${segment}

        # Stock Service - Products List
        - id: products-list
          uri: http://localhost:8082
          predicates:
            - Path=/api/stocks/products
          filters:
            - RewritePath=/api/stocks/products, /api/v1/products

        # Stock Service - Products Detail
        - id: products-detail
          uri: http://localhost:8082
          predicates:
            - Path=/api/stocks/products/**
          filters:
            - RewritePath=/api/stocks/products/(?<segment>.*), /api/v1/products/${segment}

        # Stock Service - Orders List
        - id: orders-list
          uri: http://localhost:8082
          predicates:
            - Path=/api/stocks/orders
          filters:
            - RewritePath=/api/stocks/orders, /api/v1/orders

        # Stock Service - Orders Detail
        - id: orders-detail
          uri: http://localhost:8082
          predicates:
            - Path=/api/stocks/orders/**
          filters:
            - RewritePath=/api/stocks/orders/(?<segment>.*), /api/v1/orders/${segment}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG